### ISSUE TITLE
ReferenceError: Observable is not defined

### ISSUE THREAD

**Issue by waynebrantley** [localForage/localForage-observable#21]
I have converted my app to use the new corejs as babel/polyfill is deprecated.  https://babeljs.io/docs/en/babel-polyfill

When I remove babel-polyfill from my webpack:
```
        entry: {
            'main-client': [
                "babel-polyfill",
                'react-hot-loader/patch',
                './clientApp/boot-client.tsx'
            ]
        },
```

It causes Observable is not defined.  (and this is on latest version of chrome that does not need any polyfills).  
Uncaught (in promise) ReferenceError: Observable is not defined
    at Function.newObservable.factory (localforage-observable.js:443)
    at LocalForage.newObservable (localforage-observable.js:430)

I put the babel-polyfill back and it works just fine.  Any thoughts - I noticed your zen dependency is pretty far behind, but not sure if that will fix it?

**Comment by waynebrantley** [comment]
adding 'core-js' to the entry point seems to have fixed it. Not sure why that is needed.

**Comment by thgreasi** [comment]
Hi as you can see at
https://github.com/localForage/localForage-observable/blob/fa998bc77c3763e2d9525a40fa3a2cee799da031/lib/index.ts#L178

This library doesn't import any specific Observable library, but by default relies on an Observable object being defined on the global namespace. Moreover Observable isn't yet a standardized implementation and no browser atm offers it as a backed in JS interface.
See: https://caniuse.com/#search=Observable
On the other hand it seems that core-js does offer an Observable implementation in addition of the provided polyfills and that explains why it fixes the issue for you.
See: https://github.com/zloirock/core-js#observable

In case that you want to use a specific Observable implementation, you can configure this library to do so as described in README:
https://github.com/localForage/localForage-observable#using-a-different-observable-library

I would suggest you to do so explicitly, instead of relying on the core-js included polyfill, so that you can update the version & library used independently of what core-js includes.

WRT the zen-observable dependency being outdated, this shouldn't be an issue, since it's not imported by this library's code. TBH we can turn it into a peerDependency or even a devDependency, since it's only used in the demo pages.
